apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: genie
  labels:
    app: genie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genie
  template:
    metadata:
      labels:
        app: genie
    spec:
      containers:
        - name: neo4j
          image: neo4j:3.0
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-db-cred
                  key: username
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-db-cred
                  key: password
            - name: MB_DB_HOST
              value: "localhost"
            - name: MB_DB_DBNAME
              value: "metabase"
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_PORT
              value: "9081"
        - name: cloudsql
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=verdant-abacus-130216:us-east1:funnel=tcp:9091,verdant-abacus-130216:us-east1:test-reporting-apps=tcp:9081",
                    "-credential_file=/secrets/cloudsql/cloudsql-gcp-key.json"]
          volumeMounts:
            - name: cloudsql-service-account
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-service-account
          secret:
            secretName: cloudsql-gcp-key
